### ISSUE TITLE
JMP/CALL to label gets to the wrong address

### ISSUE THREAD

**Issue by cocus** [TomNisbet/asm85#3] opened 2017-04-04 20:45 UTC
I've ported the TinyBasic from Li-Chen Wang to ASM85, the only thing I needed to address was a macro (which I replaced with a manual replace) and change some routines to match my development board.
However, there are some issues regarding jumps. The labels that are put in the beginning of the file works great, but the ones which are in lines 350+ produces a bad offset when using jmp or call.
A nice example is this snippet of the listing:
`0178 da ba 00      350: LS1:    JC   RSTART                     ;C:PASSED TXTUNF`
`017b cd c8 05      351:         CALL PRTLN                      ;PRINT THE LINE`
`017e cd 74 06      352:         CALL CHKIO                      ;STOP IF HIT CONTROL-C`
`0181 cd 36 05      353:         CALL FNDLP                      ;FIND NEXT LINE`
`0184 c3 76 01      354:         JMP  LS1                        ;AND LOOP BACK`
As you can see, at 0x0184 we got a JMP to label LS1, which is placed at 0x0178; but the opcode reflects a jump to address 0x0176, which is not correct. A lot of this errors were found regarding labels put in these lines. Just to make another example of that thing working, lets examine the line 0x178; where there is a jump if carry to label RSTART. Here is the line regarding RSTART, which is 0x00ba; matching the opcodes of 0x0178 as it should.
`00ba 31 00 c0      187: RSTART: LXI  SP,STACK`

I left an attachment with the .asm file which I'm using.
[tinybasic.asm.txt](https://github.com/TomNisbet/asm85/files/894482/tinybasic.asm.txt)

I was invoking asm85 with the following command line:
`asm85 -b 0000:3FFF tinybasic.asm`

If you need more info or you need to test something, please feel free to ask me!
Cheers

**Comment by TomNisbet** [comment] 2017-04-05 03:41
It looks like the issue is related to the expression parser.  The problem starts at the LXI H,TAB2-1 in line 308.  After that, all of the labels are off by 2.  I suspect the first pass and second pass are processing differently.  I should be able to get a fix for this in soon.

**Closed as completed** 2017-04-09 04:34 UTC
